CREATE DATABASE [TimeManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeManager', FILENAME = N'TimeManager.mdf' , SIZE = 36864KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TimeManager_log', FILENAME = N'TimeManager_log.ldf' , SIZE = 181184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TimeManager] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeManager] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TimeManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimeManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TimeManager] SET  MULTI_USER 
GO

ALTER DATABASE [TimeManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeManager] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TimeManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeManager] SET  READ_WRITE 
GO
